# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
canonical: https://gematik.de/fhir/isik/v3/Dokumentenaustausch
fhirVersion: 4.0.1
dependencies:
    ihe.iti.mhd: 4.2.0
    de.gematik.isik-basismodul: 3.0.4
    dvmd.kdl.r4.2022: 2022.1.2
FSHOnly: true
